#!/usr/bin/env bash

set -o pipefail

DOWNLOAD=https://github.com/CallyCa/cross-toolchain/releases/download/v{version}/linux-x64.tar.gz

#
# Download or build cross-toolchain
#

prebuild-install -d $DOWNLOAD || (buildDependencies && npm run build) || exit 10

#
# Restore binary symlinks
#

scripts/symlinks.sh || exit 20
